/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package classes.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class spotify extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7876337263105278815L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"spotify\",\"namespace\":\"classes.avro\",\"fields\":[{\"name\":\"id\",\"type\":[\"string\",\"null\"]},{\"name\":\"track_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"duration\",\"type\":[\"int\",\"string\",\"null\"]},{\"name\":\"explicit\",\"type\":[\"int\",\"string\",\"null\"]},{\"name\":\"popularity\",\"type\":[\"int\",\"string\",\"null\"]},{\"name\":\"acousticness\",\"type\":[\"float\",\"string\",\"null\"]},{\"name\":\"danceability\",\"type\":[\"float\",\"string\",\"null\"]},{\"name\":\"energy\",\"type\":[\"float\",\"string\",\"null\"]},{\"name\":\"instrumentalness\",\"type\":[\"float\",\"string\",\"null\"]},{\"name\":\"key\",\"type\":[\"int\",\"string\",\"null\"]},{\"name\":\"liveness\",\"type\":[\"float\",\"string\",\"null\"]},{\"name\":\"loudness\",\"type\":[\"float\",\"string\",\"null\"]},{\"name\":\"speechiness\",\"type\":[\"float\",\"string\",\"null\"]},{\"name\":\"tempo\",\"type\":[\"float\",\"string\",\"null\"]},{\"name\":\"time_signature\",\"type\":[\"int\",\"string\",\"null\"]},{\"name\":\"valence\",\"type\":[\"float\",\"string\",\"null\"]},{\"name\":\"album_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"album_type\",\"type\":[\"string\",\"null\"]},{\"name\":\"year_of_release\",\"type\":[\"int\",\"null\"]},{\"name\":\"month_of_release\",\"type\":[\"int\",\"null\"]},{\"name\":\"day_of_release\",\"type\":[\"int\",\"null\"]},{\"name\":\"weekday_of_release\",\"type\":[\"string\",\"null\"]},{\"name\":\"album_popularity\",\"type\":[\"int\",\"string\",\"null\"]},{\"name\":\"artist_name\",\"type\":[\"string\",\"null\"]},{\"name\":\"artist_popularity\",\"type\":[\"int\",\"null\",\"string\"]},{\"name\":\"followers\",\"type\":[\"int\",\"null\",\"string\"]},{\"name\":\"genre_id\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<spotify> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<spotify> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<spotify> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<spotify> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<spotify> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this spotify to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a spotify from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a spotify instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static spotify fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence track_name;
  private java.lang.Object duration;
  private java.lang.Object explicit;
  private java.lang.Object popularity;
  private java.lang.Object acousticness;
  private java.lang.Object danceability;
  private java.lang.Object energy;
  private java.lang.Object instrumentalness;
  private java.lang.Object key;
  private java.lang.Object liveness;
  private java.lang.Object loudness;
  private java.lang.Object speechiness;
  private java.lang.Object tempo;
  private java.lang.Object time_signature;
  private java.lang.Object valence;
  private java.lang.CharSequence album_name;
  private java.lang.CharSequence album_type;
  private java.lang.Integer year_of_release;
  private java.lang.Integer month_of_release;
  private java.lang.Integer day_of_release;
  private java.lang.CharSequence weekday_of_release;
  private java.lang.Object album_popularity;
  private java.lang.CharSequence artist_name;
  private java.lang.Object artist_popularity;
  private java.lang.Object followers;
  private java.lang.CharSequence genre_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public spotify() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param track_name The new value for track_name
   * @param duration The new value for duration
   * @param explicit The new value for explicit
   * @param popularity The new value for popularity
   * @param acousticness The new value for acousticness
   * @param danceability The new value for danceability
   * @param energy The new value for energy
   * @param instrumentalness The new value for instrumentalness
   * @param key The new value for key
   * @param liveness The new value for liveness
   * @param loudness The new value for loudness
   * @param speechiness The new value for speechiness
   * @param tempo The new value for tempo
   * @param time_signature The new value for time_signature
   * @param valence The new value for valence
   * @param album_name The new value for album_name
   * @param album_type The new value for album_type
   * @param year_of_release The new value for year_of_release
   * @param month_of_release The new value for month_of_release
   * @param day_of_release The new value for day_of_release
   * @param weekday_of_release The new value for weekday_of_release
   * @param album_popularity The new value for album_popularity
   * @param artist_name The new value for artist_name
   * @param artist_popularity The new value for artist_popularity
   * @param followers The new value for followers
   * @param genre_id The new value for genre_id
   */
  public spotify(java.lang.CharSequence id, java.lang.CharSequence track_name, java.lang.Object duration, java.lang.Object explicit, java.lang.Object popularity, java.lang.Object acousticness, java.lang.Object danceability, java.lang.Object energy, java.lang.Object instrumentalness, java.lang.Object key, java.lang.Object liveness, java.lang.Object loudness, java.lang.Object speechiness, java.lang.Object tempo, java.lang.Object time_signature, java.lang.Object valence, java.lang.CharSequence album_name, java.lang.CharSequence album_type, java.lang.Integer year_of_release, java.lang.Integer month_of_release, java.lang.Integer day_of_release, java.lang.CharSequence weekday_of_release, java.lang.Object album_popularity, java.lang.CharSequence artist_name, java.lang.Object artist_popularity, java.lang.Object followers, java.lang.CharSequence genre_id) {
    this.id = id;
    this.track_name = track_name;
    this.duration = duration;
    this.explicit = explicit;
    this.popularity = popularity;
    this.acousticness = acousticness;
    this.danceability = danceability;
    this.energy = energy;
    this.instrumentalness = instrumentalness;
    this.key = key;
    this.liveness = liveness;
    this.loudness = loudness;
    this.speechiness = speechiness;
    this.tempo = tempo;
    this.time_signature = time_signature;
    this.valence = valence;
    this.album_name = album_name;
    this.album_type = album_type;
    this.year_of_release = year_of_release;
    this.month_of_release = month_of_release;
    this.day_of_release = day_of_release;
    this.weekday_of_release = weekday_of_release;
    this.album_popularity = album_popularity;
    this.artist_name = artist_name;
    this.artist_popularity = artist_popularity;
    this.followers = followers;
    this.genre_id = genre_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return track_name;
    case 2: return duration;
    case 3: return explicit;
    case 4: return popularity;
    case 5: return acousticness;
    case 6: return danceability;
    case 7: return energy;
    case 8: return instrumentalness;
    case 9: return key;
    case 10: return liveness;
    case 11: return loudness;
    case 12: return speechiness;
    case 13: return tempo;
    case 14: return time_signature;
    case 15: return valence;
    case 16: return album_name;
    case 17: return album_type;
    case 18: return year_of_release;
    case 19: return month_of_release;
    case 20: return day_of_release;
    case 21: return weekday_of_release;
    case 22: return album_popularity;
    case 23: return artist_name;
    case 24: return artist_popularity;
    case 25: return followers;
    case 26: return genre_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: track_name = (java.lang.CharSequence)value$; break;
    case 2: duration = value$; break;
    case 3: explicit = value$; break;
    case 4: popularity = value$; break;
    case 5: acousticness = value$; break;
    case 6: danceability = value$; break;
    case 7: energy = value$; break;
    case 8: instrumentalness = value$; break;
    case 9: key = value$; break;
    case 10: liveness = value$; break;
    case 11: loudness = value$; break;
    case 12: speechiness = value$; break;
    case 13: tempo = value$; break;
    case 14: time_signature = value$; break;
    case 15: valence = value$; break;
    case 16: album_name = (java.lang.CharSequence)value$; break;
    case 17: album_type = (java.lang.CharSequence)value$; break;
    case 18: year_of_release = (java.lang.Integer)value$; break;
    case 19: month_of_release = (java.lang.Integer)value$; break;
    case 20: day_of_release = (java.lang.Integer)value$; break;
    case 21: weekday_of_release = (java.lang.CharSequence)value$; break;
    case 22: album_popularity = value$; break;
    case 23: artist_name = (java.lang.CharSequence)value$; break;
    case 24: artist_popularity = value$; break;
    case 25: followers = value$; break;
    case 26: genre_id = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'track_name' field.
   * @return The value of the 'track_name' field.
   */
  public java.lang.CharSequence getTrackName() {
    return track_name;
  }


  /**
   * Sets the value of the 'track_name' field.
   * @param value the value to set.
   */
  public void setTrackName(java.lang.CharSequence value) {
    this.track_name = value;
  }

  /**
   * Gets the value of the 'duration' field.
   * @return The value of the 'duration' field.
   */
  public java.lang.Object getDuration() {
    return duration;
  }


  /**
   * Sets the value of the 'duration' field.
   * @param value the value to set.
   */
  public void setDuration(java.lang.Object value) {
    this.duration = value;
  }

  /**
   * Gets the value of the 'explicit' field.
   * @return The value of the 'explicit' field.
   */
  public java.lang.Object getExplicit() {
    return explicit;
  }


  /**
   * Sets the value of the 'explicit' field.
   * @param value the value to set.
   */
  public void setExplicit(java.lang.Object value) {
    this.explicit = value;
  }

  /**
   * Gets the value of the 'popularity' field.
   * @return The value of the 'popularity' field.
   */
  public java.lang.Object getPopularity() {
    return popularity;
  }


  /**
   * Sets the value of the 'popularity' field.
   * @param value the value to set.
   */
  public void setPopularity(java.lang.Object value) {
    this.popularity = value;
  }

  /**
   * Gets the value of the 'acousticness' field.
   * @return The value of the 'acousticness' field.
   */
  public java.lang.Object getAcousticness() {
    return acousticness;
  }


  /**
   * Sets the value of the 'acousticness' field.
   * @param value the value to set.
   */
  public void setAcousticness(java.lang.Object value) {
    this.acousticness = value;
  }

  /**
   * Gets the value of the 'danceability' field.
   * @return The value of the 'danceability' field.
   */
  public java.lang.Object getDanceability() {
    return danceability;
  }


  /**
   * Sets the value of the 'danceability' field.
   * @param value the value to set.
   */
  public void setDanceability(java.lang.Object value) {
    this.danceability = value;
  }

  /**
   * Gets the value of the 'energy' field.
   * @return The value of the 'energy' field.
   */
  public java.lang.Object getEnergy() {
    return energy;
  }


  /**
   * Sets the value of the 'energy' field.
   * @param value the value to set.
   */
  public void setEnergy(java.lang.Object value) {
    this.energy = value;
  }

  /**
   * Gets the value of the 'instrumentalness' field.
   * @return The value of the 'instrumentalness' field.
   */
  public java.lang.Object getInstrumentalness() {
    return instrumentalness;
  }


  /**
   * Sets the value of the 'instrumentalness' field.
   * @param value the value to set.
   */
  public void setInstrumentalness(java.lang.Object value) {
    this.instrumentalness = value;
  }

  /**
   * Gets the value of the 'key' field.
   * @return The value of the 'key' field.
   */
  public java.lang.Object getKey() {
    return key;
  }


  /**
   * Sets the value of the 'key' field.
   * @param value the value to set.
   */
  public void setKey(java.lang.Object value) {
    this.key = value;
  }

  /**
   * Gets the value of the 'liveness' field.
   * @return The value of the 'liveness' field.
   */
  public java.lang.Object getLiveness() {
    return liveness;
  }


  /**
   * Sets the value of the 'liveness' field.
   * @param value the value to set.
   */
  public void setLiveness(java.lang.Object value) {
    this.liveness = value;
  }

  /**
   * Gets the value of the 'loudness' field.
   * @return The value of the 'loudness' field.
   */
  public java.lang.Object getLoudness() {
    return loudness;
  }


  /**
   * Sets the value of the 'loudness' field.
   * @param value the value to set.
   */
  public void setLoudness(java.lang.Object value) {
    this.loudness = value;
  }

  /**
   * Gets the value of the 'speechiness' field.
   * @return The value of the 'speechiness' field.
   */
  public java.lang.Object getSpeechiness() {
    return speechiness;
  }


  /**
   * Sets the value of the 'speechiness' field.
   * @param value the value to set.
   */
  public void setSpeechiness(java.lang.Object value) {
    this.speechiness = value;
  }

  /**
   * Gets the value of the 'tempo' field.
   * @return The value of the 'tempo' field.
   */
  public java.lang.Object getTempo() {
    return tempo;
  }


  /**
   * Sets the value of the 'tempo' field.
   * @param value the value to set.
   */
  public void setTempo(java.lang.Object value) {
    this.tempo = value;
  }

  /**
   * Gets the value of the 'time_signature' field.
   * @return The value of the 'time_signature' field.
   */
  public java.lang.Object getTimeSignature() {
    return time_signature;
  }


  /**
   * Sets the value of the 'time_signature' field.
   * @param value the value to set.
   */
  public void setTimeSignature(java.lang.Object value) {
    this.time_signature = value;
  }

  /**
   * Gets the value of the 'valence' field.
   * @return The value of the 'valence' field.
   */
  public java.lang.Object getValence() {
    return valence;
  }


  /**
   * Sets the value of the 'valence' field.
   * @param value the value to set.
   */
  public void setValence(java.lang.Object value) {
    this.valence = value;
  }

  /**
   * Gets the value of the 'album_name' field.
   * @return The value of the 'album_name' field.
   */
  public java.lang.CharSequence getAlbumName() {
    return album_name;
  }


  /**
   * Sets the value of the 'album_name' field.
   * @param value the value to set.
   */
  public void setAlbumName(java.lang.CharSequence value) {
    this.album_name = value;
  }

  /**
   * Gets the value of the 'album_type' field.
   * @return The value of the 'album_type' field.
   */
  public java.lang.CharSequence getAlbumType() {
    return album_type;
  }


  /**
   * Sets the value of the 'album_type' field.
   * @param value the value to set.
   */
  public void setAlbumType(java.lang.CharSequence value) {
    this.album_type = value;
  }

  /**
   * Gets the value of the 'year_of_release' field.
   * @return The value of the 'year_of_release' field.
   */
  public java.lang.Integer getYearOfRelease() {
    return year_of_release;
  }


  /**
   * Sets the value of the 'year_of_release' field.
   * @param value the value to set.
   */
  public void setYearOfRelease(java.lang.Integer value) {
    this.year_of_release = value;
  }

  /**
   * Gets the value of the 'month_of_release' field.
   * @return The value of the 'month_of_release' field.
   */
  public java.lang.Integer getMonthOfRelease() {
    return month_of_release;
  }


  /**
   * Sets the value of the 'month_of_release' field.
   * @param value the value to set.
   */
  public void setMonthOfRelease(java.lang.Integer value) {
    this.month_of_release = value;
  }

  /**
   * Gets the value of the 'day_of_release' field.
   * @return The value of the 'day_of_release' field.
   */
  public java.lang.Integer getDayOfRelease() {
    return day_of_release;
  }


  /**
   * Sets the value of the 'day_of_release' field.
   * @param value the value to set.
   */
  public void setDayOfRelease(java.lang.Integer value) {
    this.day_of_release = value;
  }

  /**
   * Gets the value of the 'weekday_of_release' field.
   * @return The value of the 'weekday_of_release' field.
   */
  public java.lang.CharSequence getWeekdayOfRelease() {
    return weekday_of_release;
  }


  /**
   * Sets the value of the 'weekday_of_release' field.
   * @param value the value to set.
   */
  public void setWeekdayOfRelease(java.lang.CharSequence value) {
    this.weekday_of_release = value;
  }

  /**
   * Gets the value of the 'album_popularity' field.
   * @return The value of the 'album_popularity' field.
   */
  public java.lang.Object getAlbumPopularity() {
    return album_popularity;
  }


  /**
   * Sets the value of the 'album_popularity' field.
   * @param value the value to set.
   */
  public void setAlbumPopularity(java.lang.Object value) {
    this.album_popularity = value;
  }

  /**
   * Gets the value of the 'artist_name' field.
   * @return The value of the 'artist_name' field.
   */
  public java.lang.CharSequence getArtistName() {
    return artist_name;
  }


  /**
   * Sets the value of the 'artist_name' field.
   * @param value the value to set.
   */
  public void setArtistName(java.lang.CharSequence value) {
    this.artist_name = value;
  }

  /**
   * Gets the value of the 'artist_popularity' field.
   * @return The value of the 'artist_popularity' field.
   */
  public java.lang.Object getArtistPopularity() {
    return artist_popularity;
  }


  /**
   * Sets the value of the 'artist_popularity' field.
   * @param value the value to set.
   */
  public void setArtistPopularity(java.lang.Object value) {
    this.artist_popularity = value;
  }

  /**
   * Gets the value of the 'followers' field.
   * @return The value of the 'followers' field.
   */
  public java.lang.Object getFollowers() {
    return followers;
  }


  /**
   * Sets the value of the 'followers' field.
   * @param value the value to set.
   */
  public void setFollowers(java.lang.Object value) {
    this.followers = value;
  }

  /**
   * Gets the value of the 'genre_id' field.
   * @return The value of the 'genre_id' field.
   */
  public java.lang.CharSequence getGenreId() {
    return genre_id;
  }


  /**
   * Sets the value of the 'genre_id' field.
   * @param value the value to set.
   */
  public void setGenreId(java.lang.CharSequence value) {
    this.genre_id = value;
  }

  /**
   * Creates a new spotify RecordBuilder.
   * @return A new spotify RecordBuilder
   */
  public static classes.avro.spotify.Builder newBuilder() {
    return new classes.avro.spotify.Builder();
  }

  /**
   * Creates a new spotify RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new spotify RecordBuilder
   */
  public static classes.avro.spotify.Builder newBuilder(classes.avro.spotify.Builder other) {
    if (other == null) {
      return new classes.avro.spotify.Builder();
    } else {
      return new classes.avro.spotify.Builder(other);
    }
  }

  /**
   * Creates a new spotify RecordBuilder by copying an existing spotify instance.
   * @param other The existing instance to copy.
   * @return A new spotify RecordBuilder
   */
  public static classes.avro.spotify.Builder newBuilder(classes.avro.spotify other) {
    if (other == null) {
      return new classes.avro.spotify.Builder();
    } else {
      return new classes.avro.spotify.Builder(other);
    }
  }

  /**
   * RecordBuilder for spotify instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<spotify>
    implements org.apache.avro.data.RecordBuilder<spotify> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence track_name;
    private java.lang.Object duration;
    private java.lang.Object explicit;
    private java.lang.Object popularity;
    private java.lang.Object acousticness;
    private java.lang.Object danceability;
    private java.lang.Object energy;
    private java.lang.Object instrumentalness;
    private java.lang.Object key;
    private java.lang.Object liveness;
    private java.lang.Object loudness;
    private java.lang.Object speechiness;
    private java.lang.Object tempo;
    private java.lang.Object time_signature;
    private java.lang.Object valence;
    private java.lang.CharSequence album_name;
    private java.lang.CharSequence album_type;
    private java.lang.Integer year_of_release;
    private java.lang.Integer month_of_release;
    private java.lang.Integer day_of_release;
    private java.lang.CharSequence weekday_of_release;
    private java.lang.Object album_popularity;
    private java.lang.CharSequence artist_name;
    private java.lang.Object artist_popularity;
    private java.lang.Object followers;
    private java.lang.CharSequence genre_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(classes.avro.spotify.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.track_name)) {
        this.track_name = data().deepCopy(fields()[1].schema(), other.track_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.duration)) {
        this.duration = data().deepCopy(fields()[2].schema(), other.duration);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.explicit)) {
        this.explicit = data().deepCopy(fields()[3].schema(), other.explicit);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.popularity)) {
        this.popularity = data().deepCopy(fields()[4].schema(), other.popularity);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.acousticness)) {
        this.acousticness = data().deepCopy(fields()[5].schema(), other.acousticness);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.danceability)) {
        this.danceability = data().deepCopy(fields()[6].schema(), other.danceability);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.energy)) {
        this.energy = data().deepCopy(fields()[7].schema(), other.energy);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.instrumentalness)) {
        this.instrumentalness = data().deepCopy(fields()[8].schema(), other.instrumentalness);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.key)) {
        this.key = data().deepCopy(fields()[9].schema(), other.key);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.liveness)) {
        this.liveness = data().deepCopy(fields()[10].schema(), other.liveness);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.loudness)) {
        this.loudness = data().deepCopy(fields()[11].schema(), other.loudness);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.speechiness)) {
        this.speechiness = data().deepCopy(fields()[12].schema(), other.speechiness);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.tempo)) {
        this.tempo = data().deepCopy(fields()[13].schema(), other.tempo);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.time_signature)) {
        this.time_signature = data().deepCopy(fields()[14].schema(), other.time_signature);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.valence)) {
        this.valence = data().deepCopy(fields()[15].schema(), other.valence);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.album_name)) {
        this.album_name = data().deepCopy(fields()[16].schema(), other.album_name);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.album_type)) {
        this.album_type = data().deepCopy(fields()[17].schema(), other.album_type);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.year_of_release)) {
        this.year_of_release = data().deepCopy(fields()[18].schema(), other.year_of_release);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.month_of_release)) {
        this.month_of_release = data().deepCopy(fields()[19].schema(), other.month_of_release);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
      if (isValidValue(fields()[20], other.day_of_release)) {
        this.day_of_release = data().deepCopy(fields()[20].schema(), other.day_of_release);
        fieldSetFlags()[20] = other.fieldSetFlags()[20];
      }
      if (isValidValue(fields()[21], other.weekday_of_release)) {
        this.weekday_of_release = data().deepCopy(fields()[21].schema(), other.weekday_of_release);
        fieldSetFlags()[21] = other.fieldSetFlags()[21];
      }
      if (isValidValue(fields()[22], other.album_popularity)) {
        this.album_popularity = data().deepCopy(fields()[22].schema(), other.album_popularity);
        fieldSetFlags()[22] = other.fieldSetFlags()[22];
      }
      if (isValidValue(fields()[23], other.artist_name)) {
        this.artist_name = data().deepCopy(fields()[23].schema(), other.artist_name);
        fieldSetFlags()[23] = other.fieldSetFlags()[23];
      }
      if (isValidValue(fields()[24], other.artist_popularity)) {
        this.artist_popularity = data().deepCopy(fields()[24].schema(), other.artist_popularity);
        fieldSetFlags()[24] = other.fieldSetFlags()[24];
      }
      if (isValidValue(fields()[25], other.followers)) {
        this.followers = data().deepCopy(fields()[25].schema(), other.followers);
        fieldSetFlags()[25] = other.fieldSetFlags()[25];
      }
      if (isValidValue(fields()[26], other.genre_id)) {
        this.genre_id = data().deepCopy(fields()[26].schema(), other.genre_id);
        fieldSetFlags()[26] = other.fieldSetFlags()[26];
      }
    }

    /**
     * Creates a Builder by copying an existing spotify instance
     * @param other The existing instance to copy.
     */
    private Builder(classes.avro.spotify other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.track_name)) {
        this.track_name = data().deepCopy(fields()[1].schema(), other.track_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.duration)) {
        this.duration = data().deepCopy(fields()[2].schema(), other.duration);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.explicit)) {
        this.explicit = data().deepCopy(fields()[3].schema(), other.explicit);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.popularity)) {
        this.popularity = data().deepCopy(fields()[4].schema(), other.popularity);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.acousticness)) {
        this.acousticness = data().deepCopy(fields()[5].schema(), other.acousticness);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.danceability)) {
        this.danceability = data().deepCopy(fields()[6].schema(), other.danceability);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.energy)) {
        this.energy = data().deepCopy(fields()[7].schema(), other.energy);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.instrumentalness)) {
        this.instrumentalness = data().deepCopy(fields()[8].schema(), other.instrumentalness);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.key)) {
        this.key = data().deepCopy(fields()[9].schema(), other.key);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.liveness)) {
        this.liveness = data().deepCopy(fields()[10].schema(), other.liveness);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.loudness)) {
        this.loudness = data().deepCopy(fields()[11].schema(), other.loudness);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.speechiness)) {
        this.speechiness = data().deepCopy(fields()[12].schema(), other.speechiness);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.tempo)) {
        this.tempo = data().deepCopy(fields()[13].schema(), other.tempo);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.time_signature)) {
        this.time_signature = data().deepCopy(fields()[14].schema(), other.time_signature);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.valence)) {
        this.valence = data().deepCopy(fields()[15].schema(), other.valence);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.album_name)) {
        this.album_name = data().deepCopy(fields()[16].schema(), other.album_name);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.album_type)) {
        this.album_type = data().deepCopy(fields()[17].schema(), other.album_type);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.year_of_release)) {
        this.year_of_release = data().deepCopy(fields()[18].schema(), other.year_of_release);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.month_of_release)) {
        this.month_of_release = data().deepCopy(fields()[19].schema(), other.month_of_release);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.day_of_release)) {
        this.day_of_release = data().deepCopy(fields()[20].schema(), other.day_of_release);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.weekday_of_release)) {
        this.weekday_of_release = data().deepCopy(fields()[21].schema(), other.weekday_of_release);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.album_popularity)) {
        this.album_popularity = data().deepCopy(fields()[22].schema(), other.album_popularity);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.artist_name)) {
        this.artist_name = data().deepCopy(fields()[23].schema(), other.artist_name);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.artist_popularity)) {
        this.artist_popularity = data().deepCopy(fields()[24].schema(), other.artist_popularity);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.followers)) {
        this.followers = data().deepCopy(fields()[25].schema(), other.followers);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.genre_id)) {
        this.genre_id = data().deepCopy(fields()[26].schema(), other.genre_id);
        fieldSetFlags()[26] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'track_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getTrackName() {
      return track_name;
    }


    /**
      * Sets the value of the 'track_name' field.
      * @param value The value of 'track_name'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setTrackName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.track_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'track_name' field has been set.
      * @return True if the 'track_name' field has been set, false otherwise.
      */
    public boolean hasTrackName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'track_name' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearTrackName() {
      track_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration' field.
      * @return The value.
      */
    public java.lang.Object getDuration() {
      return duration;
    }


    /**
      * Sets the value of the 'duration' field.
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setDuration(java.lang.Object value) {
      validate(fields()[2], value);
      this.duration = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'duration' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearDuration() {
      duration = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'explicit' field.
      * @return The value.
      */
    public java.lang.Object getExplicit() {
      return explicit;
    }


    /**
      * Sets the value of the 'explicit' field.
      * @param value The value of 'explicit'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setExplicit(java.lang.Object value) {
      validate(fields()[3], value);
      this.explicit = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'explicit' field has been set.
      * @return True if the 'explicit' field has been set, false otherwise.
      */
    public boolean hasExplicit() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'explicit' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearExplicit() {
      explicit = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'popularity' field.
      * @return The value.
      */
    public java.lang.Object getPopularity() {
      return popularity;
    }


    /**
      * Sets the value of the 'popularity' field.
      * @param value The value of 'popularity'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setPopularity(java.lang.Object value) {
      validate(fields()[4], value);
      this.popularity = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'popularity' field has been set.
      * @return True if the 'popularity' field has been set, false otherwise.
      */
    public boolean hasPopularity() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'popularity' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearPopularity() {
      popularity = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'acousticness' field.
      * @return The value.
      */
    public java.lang.Object getAcousticness() {
      return acousticness;
    }


    /**
      * Sets the value of the 'acousticness' field.
      * @param value The value of 'acousticness'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setAcousticness(java.lang.Object value) {
      validate(fields()[5], value);
      this.acousticness = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'acousticness' field has been set.
      * @return True if the 'acousticness' field has been set, false otherwise.
      */
    public boolean hasAcousticness() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'acousticness' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearAcousticness() {
      acousticness = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'danceability' field.
      * @return The value.
      */
    public java.lang.Object getDanceability() {
      return danceability;
    }


    /**
      * Sets the value of the 'danceability' field.
      * @param value The value of 'danceability'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setDanceability(java.lang.Object value) {
      validate(fields()[6], value);
      this.danceability = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'danceability' field has been set.
      * @return True if the 'danceability' field has been set, false otherwise.
      */
    public boolean hasDanceability() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'danceability' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearDanceability() {
      danceability = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'energy' field.
      * @return The value.
      */
    public java.lang.Object getEnergy() {
      return energy;
    }


    /**
      * Sets the value of the 'energy' field.
      * @param value The value of 'energy'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setEnergy(java.lang.Object value) {
      validate(fields()[7], value);
      this.energy = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'energy' field has been set.
      * @return True if the 'energy' field has been set, false otherwise.
      */
    public boolean hasEnergy() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'energy' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearEnergy() {
      energy = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'instrumentalness' field.
      * @return The value.
      */
    public java.lang.Object getInstrumentalness() {
      return instrumentalness;
    }


    /**
      * Sets the value of the 'instrumentalness' field.
      * @param value The value of 'instrumentalness'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setInstrumentalness(java.lang.Object value) {
      validate(fields()[8], value);
      this.instrumentalness = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'instrumentalness' field has been set.
      * @return True if the 'instrumentalness' field has been set, false otherwise.
      */
    public boolean hasInstrumentalness() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'instrumentalness' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearInstrumentalness() {
      instrumentalness = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'key' field.
      * @return The value.
      */
    public java.lang.Object getKey() {
      return key;
    }


    /**
      * Sets the value of the 'key' field.
      * @param value The value of 'key'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setKey(java.lang.Object value) {
      validate(fields()[9], value);
      this.key = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'key' field has been set.
      * @return True if the 'key' field has been set, false otherwise.
      */
    public boolean hasKey() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'key' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearKey() {
      key = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'liveness' field.
      * @return The value.
      */
    public java.lang.Object getLiveness() {
      return liveness;
    }


    /**
      * Sets the value of the 'liveness' field.
      * @param value The value of 'liveness'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setLiveness(java.lang.Object value) {
      validate(fields()[10], value);
      this.liveness = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'liveness' field has been set.
      * @return True if the 'liveness' field has been set, false otherwise.
      */
    public boolean hasLiveness() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'liveness' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearLiveness() {
      liveness = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'loudness' field.
      * @return The value.
      */
    public java.lang.Object getLoudness() {
      return loudness;
    }


    /**
      * Sets the value of the 'loudness' field.
      * @param value The value of 'loudness'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setLoudness(java.lang.Object value) {
      validate(fields()[11], value);
      this.loudness = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'loudness' field has been set.
      * @return True if the 'loudness' field has been set, false otherwise.
      */
    public boolean hasLoudness() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'loudness' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearLoudness() {
      loudness = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'speechiness' field.
      * @return The value.
      */
    public java.lang.Object getSpeechiness() {
      return speechiness;
    }


    /**
      * Sets the value of the 'speechiness' field.
      * @param value The value of 'speechiness'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setSpeechiness(java.lang.Object value) {
      validate(fields()[12], value);
      this.speechiness = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'speechiness' field has been set.
      * @return True if the 'speechiness' field has been set, false otherwise.
      */
    public boolean hasSpeechiness() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'speechiness' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearSpeechiness() {
      speechiness = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'tempo' field.
      * @return The value.
      */
    public java.lang.Object getTempo() {
      return tempo;
    }


    /**
      * Sets the value of the 'tempo' field.
      * @param value The value of 'tempo'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setTempo(java.lang.Object value) {
      validate(fields()[13], value);
      this.tempo = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'tempo' field has been set.
      * @return True if the 'tempo' field has been set, false otherwise.
      */
    public boolean hasTempo() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'tempo' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearTempo() {
      tempo = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'time_signature' field.
      * @return The value.
      */
    public java.lang.Object getTimeSignature() {
      return time_signature;
    }


    /**
      * Sets the value of the 'time_signature' field.
      * @param value The value of 'time_signature'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setTimeSignature(java.lang.Object value) {
      validate(fields()[14], value);
      this.time_signature = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'time_signature' field has been set.
      * @return True if the 'time_signature' field has been set, false otherwise.
      */
    public boolean hasTimeSignature() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'time_signature' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearTimeSignature() {
      time_signature = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'valence' field.
      * @return The value.
      */
    public java.lang.Object getValence() {
      return valence;
    }


    /**
      * Sets the value of the 'valence' field.
      * @param value The value of 'valence'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setValence(java.lang.Object value) {
      validate(fields()[15], value);
      this.valence = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'valence' field has been set.
      * @return True if the 'valence' field has been set, false otherwise.
      */
    public boolean hasValence() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'valence' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearValence() {
      valence = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'album_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getAlbumName() {
      return album_name;
    }


    /**
      * Sets the value of the 'album_name' field.
      * @param value The value of 'album_name'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setAlbumName(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.album_name = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'album_name' field has been set.
      * @return True if the 'album_name' field has been set, false otherwise.
      */
    public boolean hasAlbumName() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'album_name' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearAlbumName() {
      album_name = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'album_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getAlbumType() {
      return album_type;
    }


    /**
      * Sets the value of the 'album_type' field.
      * @param value The value of 'album_type'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setAlbumType(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.album_type = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'album_type' field has been set.
      * @return True if the 'album_type' field has been set, false otherwise.
      */
    public boolean hasAlbumType() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'album_type' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearAlbumType() {
      album_type = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'year_of_release' field.
      * @return The value.
      */
    public java.lang.Integer getYearOfRelease() {
      return year_of_release;
    }


    /**
      * Sets the value of the 'year_of_release' field.
      * @param value The value of 'year_of_release'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setYearOfRelease(java.lang.Integer value) {
      validate(fields()[18], value);
      this.year_of_release = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'year_of_release' field has been set.
      * @return True if the 'year_of_release' field has been set, false otherwise.
      */
    public boolean hasYearOfRelease() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'year_of_release' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearYearOfRelease() {
      year_of_release = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'month_of_release' field.
      * @return The value.
      */
    public java.lang.Integer getMonthOfRelease() {
      return month_of_release;
    }


    /**
      * Sets the value of the 'month_of_release' field.
      * @param value The value of 'month_of_release'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setMonthOfRelease(java.lang.Integer value) {
      validate(fields()[19], value);
      this.month_of_release = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'month_of_release' field has been set.
      * @return True if the 'month_of_release' field has been set, false otherwise.
      */
    public boolean hasMonthOfRelease() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'month_of_release' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearMonthOfRelease() {
      month_of_release = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'day_of_release' field.
      * @return The value.
      */
    public java.lang.Integer getDayOfRelease() {
      return day_of_release;
    }


    /**
      * Sets the value of the 'day_of_release' field.
      * @param value The value of 'day_of_release'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setDayOfRelease(java.lang.Integer value) {
      validate(fields()[20], value);
      this.day_of_release = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'day_of_release' field has been set.
      * @return True if the 'day_of_release' field has been set, false otherwise.
      */
    public boolean hasDayOfRelease() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'day_of_release' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearDayOfRelease() {
      day_of_release = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'weekday_of_release' field.
      * @return The value.
      */
    public java.lang.CharSequence getWeekdayOfRelease() {
      return weekday_of_release;
    }


    /**
      * Sets the value of the 'weekday_of_release' field.
      * @param value The value of 'weekday_of_release'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setWeekdayOfRelease(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.weekday_of_release = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'weekday_of_release' field has been set.
      * @return True if the 'weekday_of_release' field has been set, false otherwise.
      */
    public boolean hasWeekdayOfRelease() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'weekday_of_release' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearWeekdayOfRelease() {
      weekday_of_release = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'album_popularity' field.
      * @return The value.
      */
    public java.lang.Object getAlbumPopularity() {
      return album_popularity;
    }


    /**
      * Sets the value of the 'album_popularity' field.
      * @param value The value of 'album_popularity'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setAlbumPopularity(java.lang.Object value) {
      validate(fields()[22], value);
      this.album_popularity = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'album_popularity' field has been set.
      * @return True if the 'album_popularity' field has been set, false otherwise.
      */
    public boolean hasAlbumPopularity() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'album_popularity' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearAlbumPopularity() {
      album_popularity = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'artist_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getArtistName() {
      return artist_name;
    }


    /**
      * Sets the value of the 'artist_name' field.
      * @param value The value of 'artist_name'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setArtistName(java.lang.CharSequence value) {
      validate(fields()[23], value);
      this.artist_name = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'artist_name' field has been set.
      * @return True if the 'artist_name' field has been set, false otherwise.
      */
    public boolean hasArtistName() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'artist_name' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearArtistName() {
      artist_name = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'artist_popularity' field.
      * @return The value.
      */
    public java.lang.Object getArtistPopularity() {
      return artist_popularity;
    }


    /**
      * Sets the value of the 'artist_popularity' field.
      * @param value The value of 'artist_popularity'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setArtistPopularity(java.lang.Object value) {
      validate(fields()[24], value);
      this.artist_popularity = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'artist_popularity' field has been set.
      * @return True if the 'artist_popularity' field has been set, false otherwise.
      */
    public boolean hasArtistPopularity() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'artist_popularity' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearArtistPopularity() {
      artist_popularity = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'followers' field.
      * @return The value.
      */
    public java.lang.Object getFollowers() {
      return followers;
    }


    /**
      * Sets the value of the 'followers' field.
      * @param value The value of 'followers'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setFollowers(java.lang.Object value) {
      validate(fields()[25], value);
      this.followers = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'followers' field has been set.
      * @return True if the 'followers' field has been set, false otherwise.
      */
    public boolean hasFollowers() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'followers' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearFollowers() {
      followers = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'genre_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getGenreId() {
      return genre_id;
    }


    /**
      * Sets the value of the 'genre_id' field.
      * @param value The value of 'genre_id'.
      * @return This builder.
      */
    public classes.avro.spotify.Builder setGenreId(java.lang.CharSequence value) {
      validate(fields()[26], value);
      this.genre_id = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'genre_id' field has been set.
      * @return True if the 'genre_id' field has been set, false otherwise.
      */
    public boolean hasGenreId() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'genre_id' field.
      * @return This builder.
      */
    public classes.avro.spotify.Builder clearGenreId() {
      genre_id = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public spotify build() {
      try {
        spotify record = new spotify();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.track_name = fieldSetFlags()[1] ? this.track_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.duration = fieldSetFlags()[2] ? this.duration :  defaultValue(fields()[2]);
        record.explicit = fieldSetFlags()[3] ? this.explicit :  defaultValue(fields()[3]);
        record.popularity = fieldSetFlags()[4] ? this.popularity :  defaultValue(fields()[4]);
        record.acousticness = fieldSetFlags()[5] ? this.acousticness :  defaultValue(fields()[5]);
        record.danceability = fieldSetFlags()[6] ? this.danceability :  defaultValue(fields()[6]);
        record.energy = fieldSetFlags()[7] ? this.energy :  defaultValue(fields()[7]);
        record.instrumentalness = fieldSetFlags()[8] ? this.instrumentalness :  defaultValue(fields()[8]);
        record.key = fieldSetFlags()[9] ? this.key :  defaultValue(fields()[9]);
        record.liveness = fieldSetFlags()[10] ? this.liveness :  defaultValue(fields()[10]);
        record.loudness = fieldSetFlags()[11] ? this.loudness :  defaultValue(fields()[11]);
        record.speechiness = fieldSetFlags()[12] ? this.speechiness :  defaultValue(fields()[12]);
        record.tempo = fieldSetFlags()[13] ? this.tempo :  defaultValue(fields()[13]);
        record.time_signature = fieldSetFlags()[14] ? this.time_signature :  defaultValue(fields()[14]);
        record.valence = fieldSetFlags()[15] ? this.valence :  defaultValue(fields()[15]);
        record.album_name = fieldSetFlags()[16] ? this.album_name : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.album_type = fieldSetFlags()[17] ? this.album_type : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.year_of_release = fieldSetFlags()[18] ? this.year_of_release : (java.lang.Integer) defaultValue(fields()[18]);
        record.month_of_release = fieldSetFlags()[19] ? this.month_of_release : (java.lang.Integer) defaultValue(fields()[19]);
        record.day_of_release = fieldSetFlags()[20] ? this.day_of_release : (java.lang.Integer) defaultValue(fields()[20]);
        record.weekday_of_release = fieldSetFlags()[21] ? this.weekday_of_release : (java.lang.CharSequence) defaultValue(fields()[21]);
        record.album_popularity = fieldSetFlags()[22] ? this.album_popularity :  defaultValue(fields()[22]);
        record.artist_name = fieldSetFlags()[23] ? this.artist_name : (java.lang.CharSequence) defaultValue(fields()[23]);
        record.artist_popularity = fieldSetFlags()[24] ? this.artist_popularity :  defaultValue(fields()[24]);
        record.followers = fieldSetFlags()[25] ? this.followers :  defaultValue(fields()[25]);
        record.genre_id = fieldSetFlags()[26] ? this.genre_id : (java.lang.CharSequence) defaultValue(fields()[26]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<spotify>
    WRITER$ = (org.apache.avro.io.DatumWriter<spotify>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<spotify>
    READER$ = (org.apache.avro.io.DatumReader<spotify>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










